### ISSUE TITLE
Incorrect naming of some functions

### ISSUE THREAD

**Issue by CodeZilla7** [googlecodelabs/kotlin-coroutines#11]
Hello @objcode I also found some minor issues in the naming of some functions. For example in [Using Kotlin Coroutines in your Android App](https://codelabs.developers.google.com/codelabs/kotlin-coroutines/#3)

`// Slow request with coroutines
@UiThread
suspend fun makeNetworkRequest() {
    // slowNetworkRequest is another suspend function so instead of 
    // blocking the main thread  makeNetworkRequest will `suspend` until the result is 
    // ready
    val result = slowFetch()
    // continue to execute after the result is ready
    show(result)
}

suspend fun slowFetch(): SlowResult { ... }`

`slowNetworkRequest` is not present and should be `slowFetch` instead. Just a minor issue, thanks!

**Comment by objcode** [comment]
Thanks, good catch! I'll update the codelab with the correct names.
