### ISSUE TITLE
Fix: The Avocado

### ISSUE THREAD

**Issue by ch22843** [googlecodelabs/kotlin-coroutines#110]
### Step 4: Plants with custom sorting

I think something is wrong in this codelab. Because the Avocado is not disapearing from list when press filter icon.

![image](https://user-images.githubusercontent.com/35041019/96502496-eac7f500-1262-11eb-9591-f27379bf0080.png)

**Comment by AhmedMousa7** [comment]
I think the correct should be (the **Sunflower** disappears from the list since its GrowZone is not 9.)

**Comment by sfreeman28** [comment]
Agreed. Sunflower has growZoneNumber of 8

**Comment by wojtek-kalicinski** [comment]
Thank you, I've corrected the text in the internal codelab source document and it will be visible soon, once we publish a new version on the website.
