### ISSUE TITLE
`customSortFlow` in "11. Combining flows declaratively"

### ISSUE THREAD

**Issue by naco-siren** [googlecodelabs/kotlin-coroutines#116]
![image](https://user-images.githubusercontent.com/8222638/99946471-44708300-2d2b-11eb-8ef1-215783748f6f.png)

I honestly don't know what this block is meant for or how to fix it.

![image](https://user-images.githubusercontent.com/8222638/99946564-679b3280-2d2b-11eb-9b61-7c9681cba7d2.png)

**Comment by antonkovalyov351** [comment]
Should be:
```
    private val customSortFlow = plantsListSortOrderCache::getOrAwait.asFlow()
        .onStart {
            emit(listOf())
            delay(1500)
        }
```

**Comment by ravisara** [comment]
> Should be:
> 
> ```
>     private val customSortFlow = plantsListSortOrderCache::getOrAwait.asFlow()
>         .onStart {
>             emit(listOf())
>             delay(1500)
>         }
> ```

Thanks Anton, the code you've posted above seems to work for me too. Incidentally, when I put a delay of 6000 instead of 1500, the effect is clearly noticeable.

**Comment by wojtek-kalicinski** [comment]
Thank you, I've corrected the text in the internal codelab source document and it will be visible soon, once we publish a new version on the website.
