### ISSUE TITLE
A typo in "14. Controlling concurrency with flow"

### ISSUE THREAD

**Issue by naco-siren** [googlecodelabs/kotlin-coroutines#117]
![image](https://user-images.githubusercontent.com/8222638/99948034-ab8f3700-2d2d-11eb-8484-8246bd317294.png)

A `}` is missing before `else`:
```kotlin
    if (growZone == NoGrowZone) {
        plantRepository.tryUpdateRecentPlantsCache()
     else {
        .tryUpdateRecentPlantsForGrowZoneCache(growZone)
     }
```

**Comment by wojtek-kalicinski** [comment]
Thank you, I've corrected the text in the internal codelab source document and it will be visible soon, once we publish a new version on the website.
