### ISSUE TITLE
advanced-kotlin-coroutines#3

### ISSUE THREAD

**Issue by DanteAndroid** [googlecodelabs/kotlin-coroutines#118]
https://codelabs.developers.google.com/codelabs/advanced-kotlin-coroutines#3

>Now if the filter button is pressed (and only GrowZone 9 plants are displayed), the **Avocado** disappears from the list since its GrowZone is not 9. The other three plants in the custom sort list are in GrowZone 9, so they'll remain at the top of the list. The only other plant in GrowZone 9 is the Tomato, which appears last in this list.

Says Avocado but the image shows **Sunflower** disappears.

**Comment by wojtek-kalicinski** [comment]
Thank you, I've corrected the text in the internal codelab source document and it will be visible soon, once we publish a new version on the website.
