### ISSUE TITLE
Unresolved reference: ConsumableValue

### ISSUE THREAD

**Issue by jeffbarge** [googlecodelabs/kotlin-coroutines#12]
Sure would be nice if the code lab starter project actually compiled...

```kotlin-coroutines-start/app/src/main/java/com/example/android/kotlincoroutines/main/MainViewModel.kt: (48, 53): Unresolved reference: ConsumableValue```

**Comment by narko** [comment]
Same issue here. It seems there were some problems during the refactoring. The code is actually here. I am creating a PR now with the fix.

**Comment by objcode** [comment]
Thanks for the report! I've just merged  https://github.com/googlecodelabs/kotlin-coroutines/pull/16 which fixes this.

**Comment by andre-artus** [comment]
Was the intention only to remove ConsumableValue from the start project? Or has something changed to necessitate its removal?

**Comment by objcode** [comment]
After discussion we decided that it was unnecessary complexity to show in samples like this. It's a reasonable way to do it in your app if you're comfortable with that style and your team is ok with it.

Reviewing the code for ConsumableValue it was fairly dense code and unrelated to introducing coroutines.

The pattern implemented in the current codelab is our starting recommendation - it preserves the contract that LiveData will always return the last value that was emitted whenever it's queried from the UI thread. As you add abstractions to encapsulate this, trying to maintain that contract is a good idea.
