### ISSUE TITLE
getPlantsWithGrowZoneNumber instead of getPlantsWithGrowZoneFlow in Step 13

### ISSUE THREAD

**Issue by MelerosPaw** [googlecodelabs/kotlin-coroutines#120]
Under subtitle "Using suspend functions to orchestrate async work" there is this sentence:

> Open up PlantsRepository.kt and add a map transform to getPlantsWithGrowZoneNumber.

But the accompanying snippet indicates method getPlantsWithGrowZoneFlow instead.

**Comment by wojtek-kalicinski** [comment]
Thank you, I've corrected the text in the internal codelab source document and it will be visible soon, once we publish a new version on the website.
