### ISSUE TITLE
"make the value" should be "make sure the value"

### ISSUE THREAD

**Issue by MelerosPaw** [googlecodelabs/kotlin-coroutines#121]
Under subtitle "Using suspend functions to orchestrate async work" there is this paragraph where that word is missing.

> If you do launch another coroutine inside a flow operation like we're doing here inside getOrAwait and applyMainSafeSort, make the value is returned to the original coroutine before emitting it.

**Comment by wojtek-kalicinski** [comment]
Thank you, I've corrected the text in the internal codelab source document and it will be visible soon, once we publish a new version on the website.
