### ISSUE TITLE
In step 6, "if the either the database or network call fails." should be "if either the database or network call fails."

### ISSUE THREAD

**Issue by ravisara** [googlecodelabs/kotlin-coroutines#124]
I.e possible typo in the following step(Step 6):
https://codelabs.developers.google.com/codelabs/advanced-kotlin-coroutines#5

**Comment by wojtek-kalicinski** [comment]
Thank you, I've corrected the text in the internal codelab source document and it will be visible soon, once we publish a new version on the website.
