### ISSUE TITLE
i opened this project in android studio from "start" folder , but android studio throwing some error.

### ISSUE THREAD

**Issue by shubham7400** [googlecodelabs/kotlin-coroutines#125]
Task 'wrapper' not found in project ':start'. 
 this line is getting print

**Comment by stfnjanson** [comment]
Same here with project finished_code

When adding this to build.gradle:

task wrapper(type: Wrapper){
   gradleVersion = '2.14.1'
}

the next error message is:
Task 'prepareKotlinBuildScriptModel' not found in project ':finished_code'.

**Comment by wojtek-kalicinski** [comment]
Did you try with the code I commited yesterday? It should fix both issues. 
Also make sure you don't open the `start` or `finished_code` , but the root project - `advanced-coroutines-codelab`

Please reopen if this is still a problem.
