### ISSUE TITLE
Last code snippet in Step 12 has 3 duplicate import lines

### ISSUE THREAD

**Issue by oscardelgado** [googlecodelabs/kotlin-coroutines#128]
import android.content.Context
import androidx.test.core.app.ApplicationProvider
import androidx.work.ListenableWorker.Result
import android.content.Context
import androidx.test.core.app.ApplicationProvider
import androidx.work.ListenableWorker.Result
...

**Comment by wojtek-kalicinski** [comment]
Thank you, I've corrected the text in the internal codelab source document and it will be visible soon, once we publish a new version on the website.
