### ISSUE TITLE
Implement CoroutineScope instead of declaring it as a property

### ISSUE THREAD

**Issue by SaeedMasoumi** [googlecodelabs/kotlin-coroutines#14]
I think it's better to make `MainViewModel` to implement `CoroutineScope` insead of declaring it as a property, so every `uiScope.launch { .. }` can be replaced by `launch { ... }`.

**Comment by CodeZilla7** [comment]
I think the property is better because what if I'd like to use another dispatcher other than the Main? withContext might help but we'd like to get a reference to the Job to maybe cancel it later on.

**Comment by SaeedMasoumi** [comment]
@CodeZilla7 In this case, I prefer to use `async` and keep the reference of `Deferred<T>`. It's a non-blocking cancelable future.

**Comment by narko** [comment]
Do you guys get an IDE complaint when using uiScope.launch? In my case case, AS tells me "Unsupported [cannot use release coroutines with api version less than 1.3]". Gradle and AS seem to be configured fine and using kotlin version 1.3.

**Comment by CodeZilla7** [comment]
> Do you guys get an IDE complaint when using uiScope.launch? In my case case, AS tells me "Unsupported [cannot use release coroutines with api version less than 1.3]". Gradle and AS seem to be configured fine and using kotlin version 1.3. The app still runs though.

I don't have any error in my end. Try Invalidate Cache and Restart. But first double check if you're using the stable versions.

**Comment by narko** [comment]
@CodeZilla7 invalidating got rid of the issue. Cheers! :)

**Comment by objcode** [comment]
That has the side effect of exposing launch as part of the public API of the ViewModel, hence why it prefers to use composition in this context.
