### ISSUE TITLE
Broken link: Advanced Coroutines with Kotlin Flow and LiveData

### ISSUE THREAD

**Issue by shervinkoushan** [googlecodelabs/kotlin-coroutines#143]
The last step [here ](https://developer.android.com/codelabs/kotlin-coroutines#12) mentions another code lab, but the link is broken. The correct link seems to be: https://developer.android.com/codelabs/advanced-kotlin-coroutines#0

**Comment by osuleymanova** [comment]
Duplicate of #141

**Comment by osuleymanova** [comment]
@shervinkoushan 
Thank you for reaching out to us. The issue is fixed and published.
