### ISSUE TITLE
App crashes on Android S+ because of missing Flag in executePendingIntent()

### ISSUE THREAD

**Issue by tillkrempel** [googlecodelabs/kotlin-coroutines#158]
When trying to do the advanced coroutines codelab using an emulator with Android S, the application crashes as the FLAG_IMMUTABLE or FLAG_MUTABLE is not set, which seems to be required on that platform version.

**Comment by JaesungLeee** [comment]
Me either :(

**Comment by lmint1** [comment]
Go to build.gradle (root) and change the work_version to 2.7.0:
```
//def work_version = '2.2.0'
def work_version = '2.7.0'
```

**Comment by katiedotson** [comment]
@lmint1 's suggestion worked, but I also had to specify the Java Version in the sunflower build.gradle:

```
compileOptions {
  sourceCompatibility JavaVersion.VERSION_1_8
  targetCompatibility JavaVersion.VERSION_1_8
}
kotlinOptions {
  jvmTarget = '1.8'
}
```
