### ISSUE TITLE
What's the spinner about?

### ISSUE THREAD

**Issue by febs** [googlecodelabs/kotlin-coroutines#19]
There's a spinner in the activity_main.xml file but I couldn't find how it's used :thinking:

**Comment by tylerbwong** [comment]
In the repository part of the code lab, it's used to indicate the [title loading](https://github.com/googlecodelabs/kotlin-coroutines/blob/master/kotlin-coroutines-repository/app/src/main/java/com/example/android/kotlincoroutines/main/MainViewModel.kt#L130). It's visibility is changed [here](https://github.com/googlecodelabs/kotlin-coroutines/blob/master/kotlin-coroutines-repository/app/src/main/java/com/example/android/kotlincoroutines/main/MainActivity.kt#L69) based on the `LiveData` value.

**Comment by objcode** [comment]
Aye, this is a loading / data / error pattern but the spinner much due to the short delay on fake network replies.
