### ISSUE TITLE
viewModelScope.launch inits on main thread

### ISSUE THREAD

**Issue by BulatMukhutdinov** [googlecodelabs/kotlin-coroutines#23]
I am using kotlin coroutines and lifecycle extensions for it, specifically viewModelScope. I also turned on StrictMode. When I call 
```
viewModelScope.launch {}
```
in viewModel I have an error
```
StrictMode ThreadPolicy violation. Caused by: android.os.strictmode.DiskReadViolation
```
Why viewModelScope uses disk read in initialization and how to init viewModelScope right (without strict mode violations)?

**Comment by objcode** [comment]
This is a known issue with debug builds that we're taking a look at. It's because it's using a service loader (any dereference of Dispatchers.Main will cause this to happen)

**Comment by LouisCAD** [comment]
@BulatMukhutdinov A workaround is to eagerly access `Dispatchers.Main` before running the code enabling strict mode, and run this code when in release mode, alongside R8 from AGP 3.5 (beta or newer) being enabled: `System.setProperty("kotlinx.coroutines.fast.service.loader", "false")`. R8 will strip service loader usage away, and you'll still get the "fast" one in debug.

**Comment by BulatMukhutdinov** [comment]
@LouisCAD is it possible on stable versions?

Also, you said ```run this code when in release mode```. And in the end ```you'll still get the "fast" one in debug.```. Does it mean that this code (```System.setProperty("kotlinx.coroutines.fast.service.loader", "false")```) should be added (and will work) for both build types?
Thanks

**Comment by LouisCAD** [comment]
@BulatMukhutdinov
Adding the following R8 rules (in your `proguard-rules.pro` file) should do the trick:
```
# Entry point for retaining MainDispatcherLoader which uses a ServiceLoader.
-keep class kotlinx.coroutines.Dispatchers {
  ** getMain();
}

 # Entry point for retaining CoroutineExceptionHandlerImpl.handlers which uses a ServiceLoader.
-keep class kotlinx.coroutines.CoroutineExceptionHandlerKt {
  void handleCoroutineException(...);
}

 # Ensure the custom, fast service loader implementation is removed. In the case of fast service
# loader encountering an exception it falls back to regular ServiceLoader in a way that cannot be
# optimized out by R8.
-assumevalues class kotlinx.coroutines.internal.MainDispatcherLoader {
  boolean FAST_SERVICE_LOADER_ENABLED return false;
}
-checkdiscard class kotlinx.coroutines.internal.FastServiceLoader

 # We are cheating a bit by not having android.jar on R8's library classpath. Ignore those warnings.
-ignorewarnings
```
[Source is here](https://github.com/Kotlin/kotlinx.coroutines/pull/1245/files#diff-8205bdb61c50048e7535dd74e7a3a627).

**Comment by BulatMukhutdinov** [comment]
@LouisCAD Not sure about performance but it still fails with strict mode policy violation 
I have sample project to test on it
https://github.com/BulatMukhutdinov/music-management

**Comment by LouisCAD** [comment]
@BulatMukhutdinov It seems you enable strict mode in debug, but R8 only optimizes it if minifyEnabled is set to true, which is currently not the case for your debug build type (set only for the release build type). If you just want to use strict mode in debug without issues, just access Dispatchers.Main before intialializing strict mode as next accesses don't do I/O on the calling thread.

**Comment by BulatMukhutdinov** [comment]
It would be strange decision to enable strict mode in release builds :)
Anyway, @LouisCAD many thanks!

**Comment by objcode** [comment]
I'm going to close this as it's not an issue with the codelab. However thanks for raising the issue we've prioritized cleaning this up.

Cheers,
Sean
