### ISSUE TITLE
Bad variable name in step 6

### ISSUE THREAD

**Issue by jinqian** [googlecodelabs/kotlin-coroutines#33]
https://codelabs.developers.google.com/codelabs/kotlin-coroutines/index.html#5

At the end of the step, in the test code written with the experimental API:
```kotlin
   @After
   fun teardown() {
       // reset main after the test is done
       Dispatchers.resetMain()
       // call this to ensure TestCoroutineDispater doesn't 
       // accidentally carry state to the next test
       dispatcher.cleanupTestCoroutines()
   }
```

It should be `testDispatcher.cleanupTestCoroutines()` :)

**Comment by objcode** [comment]
Thanks for the report! Working on this now.

**Comment by objcode** [comment]
Until it can be rewritten I've removed the code. Thank you!
