### ISSUE TITLE
RefreshTitle test does not return MainNetworkFake result

### ISSUE THREAD

**Issue by fitzsia2** [googlecodelabs/kotlin-coroutines#34]
I expect the [refreshTitle](https://github.com/googlecodelabs/kotlin-coroutines/blob/da13fa565fe668e50f40d02eb565c5d67da5c501/kotlin-coroutines-end/app/src/test/java/com/example/android/kotlincoroutines/main/MainViewModelUnitTest.kt#L48) test to check that after refreshTitle() is called, the MainNetworkFake result is returned by subject.title (not FakeTitleDao value). I tried to check this by changing the initialization of MainFakeNetwork and found that only the FakeTitleDao is returned. Correct me if my understanding is incorrect, but I think this is wrong. What is really being tested by refreshTitle?

**Comment by objcode** [comment]
Thanks! I've removed the test until it can be reworked!
