### ISSUE TITLE
Use suspendCancellableCoroutine instead of suspendCoroutine

### ISSUE THREAD

**Issue by qwwdfsad** [googlecodelabs/kotlin-coroutines#8]
In [`Converting existing callback APIs with coroutines`](https://codelabs.developers.google.com/codelabs/kotlin-coroutines/index.html#6) section you recommend to use `suspendCoroutine` function to convert callback-based API to suspending one.

While it is correct in general, in the context of this tutorial (with focus on `kotlinx.coroutines`) it is better to use [`suspendCancellableCoroutine`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.experimental/suspend-cancellable-coroutine.html) to make calls to API cancellable. Moreover, cancellation can be propagated to the API if it supports one.

**Comment by objcode** [comment]
Thanks!

Taking a look, I think that adds a level of complexity to this part that can be deferred. I'll add a callout box explaining that suspendCancellableCoroutine can be used instead.
