### ISSUE TITLE
Typo on first page

### ISSUE THREAD

**Issue by ink404** [googlecodelabs/kotlin-coroutines#86]
https://codelabs.developers.google.com/codelabs/advanced-kotlin-coroutines/index.html?index=..%2F..index#0

In this codelab, you'll learn how to use the LiveData builder to combine Kotlin coroutines with LiveData in an Android app. **We'll also Coroutines Asynchronous** Flow to implement the same thing, which is a coroutines library for representing an async sequence, or stream, of values.

area with typo in bold

**Comment by tiembo** [comment]
Thanks for the report! This has been fixed.
